# Generated by Django 3.1 on 2022-03-23 14:23

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('mobileNumber', models.IntegerField()),
                ('appointmentDate', models.DateField(default=time.time)),
                ('comment', models.TextField()),
            ],
        ),
    ]
