# Generated by Django 3.1 on 2022-03-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthBot', '0002_auto_20220323_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='mobileNumber',
            field=models.CharField(max_length=150),
        ),
    ]
