# Generated by Django 3.1 on 2022-03-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthBot', '0003_auto_20220323_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
